apiVersion: v1
kind: Secret
metadata:
  name: {{ include "failedkite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "failedkite.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_TOKEN: {{ required "slack.apiToken is required!" .Values.slack.apiToken | b64enc | quote }}